# action.yaml
name: "Check Changed Files"
description: "GitHub Action to check changed files in a Git repository"
author: "ZPascal"
branding:
  icon: check
  color: blue
inputs:
  checked_location:
    description: "Enter the location of the files, seperated by ;. Example: src/;docs/test.txt;tests/test*"
    required: true
  git_location:
    description: ""
    required: false
    default: ""
  check_all_files:
    description: "Enables the check of all defined files and folders in the directory"
    default: "false"
    required: false
  github_user_token:
    description: "Define the used GitHub server user token for Github.com"
    default: ${{ secrets.GITHUB_TOKEN }}
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ZPascal/check-changed-files-action
        ref: v1
        github-server-url: https://oauth2:${{ inputs.github_user_token }}@github.com

    - name: Install Python Dependencies
      run: python3 -m pip install pygit2
      shell: bash

    - name: Check the changed files (wrapper)
      run: |
        optional_flags=""
        if [ -n "${{ inputs.git_location }}" ]; then
            optional_flags+="-gl ${{ inputs.git_location }}"
        fi
        if [ "${{ inputs.check_all_files }}" == "true" ]; then
            optional_flags+=" -caf"
        fi
        python3 src/check_changed_files.py -cl "${{ inputs.checked_location }}" $optional_flags
      shell: bash
