# action.yaml
name: "Check Changed Files"
description: "GitHub Action to check changed files in a Git repository"
author: "ZPascal"
branding:
  icon: check
  color: blue
inputs:
  checked_location:
    description: "Enter the location of the files, seperated by ;. Example: src/;docs/test.txt;tests/test*"
    required: true
  git_location:
    description: ""
    required: false
    default: ""
  check_all_files:
    description: "Enables the check of all defined files and folders in the directory"
    default: "false"
    required: false
outputs:
  files_changed:
    description: "Returns true if changed files are detected and false by default"
    value: ${{ steps.check-changed-files.outputs.changed-files }}
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      run: python3 -m pip install pygit2
      shell: bash

    - name: Check the changed files (wrapper)
      id: check-changed-files
      env:
        ACTION_REF: ${{ github.action_ref }}
      run: |
        # Check if curl is installed, if not install it
        if ! command -v curl &> /dev/null; then
          echo "curl not found, installing..."
          if [ -f /etc/alpine-release ]; then
            # Alpine Linux
            apk add --no-cache curl
          elif [ -f /etc/debian_version ] || [ -f /etc/lsb-release ]; then
            # Ubuntu/Debian
            apt-get update && apt-get install -y curl
          else
            echo "Unsupported OS distribution"
            exit 1
          fi
        fi
        
        # Download the check_changed_files.py script
        echo "Downloading check_changed_files.py script..."
        echo $ACTION_REF
        curl -s -L -o /tmp/check_changed_files.py https://raw.githubusercontent.com/ZPascal/check-changed-files-action/refs/heads/$ACTION_REF/src/check_changed_files.py
        
        optional_flags=""
        if [ -n "${{ inputs.git_location }}" ]; then
            optional_flags+="-gl ${{ inputs.git_location }}"
        fi
        if [ "${{ inputs.check_all_files }}" == "true" ]; then
            optional_flags+=" -caf"
        fi
        ls -la /tmp/check_changed_files.py
        cat /tmp/check_changed_files.py
        echo "changed-files='$(python3 /tmp/check_changed_files.py -cl '${{ inputs.checked_location }}' $optional_flags)'" >> "$GITHUB_OUTPUT"
      shell: bash
